baseURL = "https://eo.lamey.me"
title = "consistently contradictory"
languageCode = "en-us"

disableHugoGeneratorInject = true
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm"]

[author]
  name = "Eric-Olivier Lamey"
